### ISSUE TITLE
name '__about__' is not defined

### ISSUE THREAD

**Issue by Heerpa** [karpierz/libusb#1]
I tried to use libusb in Python 3.7.1 running in a Docker container off of jupyter/minimal-notebook

after pip installing tox and libusb, I started python and imported libusb
`>>> import libusb`
here, I got the `NameError: name 'time_t' is not defined`
that hinted toward executing
`>>> import time`
`>>> import libusb`

and then I got stuck with the error `name '__about__' is not defined`
It seems like this might be a Python 3.7 issue,m but You state on PyPI that libusb works with Python 3.7?

**Comment by karpierz** [comment]
Sorry, but I'v mentioned in README:
"ATTENTION: currently works and tested only for Windows."
..but of course I will try also to make support for Linux but (because I am not good familiar with Linux)
please get me a time (suppose max. 1 week).

**Comment by karpierz** [comment]
1.0.22b7 is ready.
It has support for Linux x86 but did not tested on this platform.

**Comment by karpierz** [comment]
Internal tests are passed (Debian 10 buster, x64).
