### ISSUE TITLE
Cross-Platform?

### ISSUE THREAD

**Issue by s-light** [karpierz/libusb#2]
Hi @karpierz,

do you have any plans to fill the missing things for the full cross-platform support?

this would make this library the only one that is easy installable via pip and really works cross-platform!
(as fare as i found in [my research](https://github.com/jnweiger/led-badge-44x11/issues/2#issue-440190289))

as fare as i have looked you have prepared almost all things?!
only the pre-compiled lib files for the other architectures / systems are missing?

**Comment by karpierz** [comment]
> only the pre-compiled lib files for the other architectures / systems are missing?

Yes! Exactly. So.. could you help me to finish this little project ? ;)

**Comment by karpierz** [comment]
@s-light 
1.0.22b7 is ready.
It has support for Linux x86 but did not tested on this platform.
Can you check if it even starts up?

**Comment by karpierz** [comment]
Internal tests are passed (Debian 10 buster, x64).

**Comment by s-light** [comment]
thanks for adding support!
currently i don't have any time left to test - sorry.

**Comment by karpierz** [comment]
@s-light 

FYI:
1.0.22b8 is ready (1.0.22b7 has been removed).
Internal tests are passed (Debian 10 buster, x64):

(python) root@ks357281:~# git clone https://github.com/karpierz/libusb.git
Cloning into 'libusb'...
[...]
(python) root@ks357281:~# cd libusb/tests
(python) root@ks357281:~/libusb/tests# python stress.py
Starting test run: init_and_exit...
Success (0)
Starting test run: get_device_list...
Success (0)
Starting test run: many_device_lists...
Success (0)
Starting test run: default_context_change...
Success (0)
---
Ran 4 tests
Passed 4 tests
Failed 0 tests
Error in 0 tests
Skipped 0 tests
(python) root@ks357281:~/libusb/tests#
