### ISSUE TITLE
can't import libusb

### ISSUE THREAD

**Issue by Newbrict** [karpierz/libusb#3]
```
Traceback (most recent call last):
  File "test_libusb.py", line 5, in <module>
    import libusb as usb
  File "/home/plant/code/atompalm/manager/ENV/lib/python3.8/site-packages/libusb/__init__.py", line 6, in <module>
    from ._libusb import *
  File "/home/plant/code/atompalm/manager/ENV/lib/python3.8/site-packages/libusb/_libusb.py", line 28, in <module>
    from ._platform import DLL_PATH, DLL, CFUNC, dlclose
  File "/home/plant/code/atompalm/manager/ENV/lib/python3.8/site-packages/libusb/_platform/__init__.py", line 30, in <module>
    from ._linux   import DLL_PATH, DLL, CFUNC, dlclose
  File "/home/plant/code/atompalm/manager/ENV/lib/python3.8/site-packages/libusb/_platform/_linux/__init__.py", line 35, in <module>
    class timeval(ct.Structure):
  File "/home/plant/code/atompalm/manager/ENV/lib/python3.8/site-packages/libusb/_platform/_linux/__init__.py", line 37, in timeval
    ("tv_sec",  time_t),       # seconds
NameError: name 'time_t' is not defined
```

This is the error I'm getting with python 3.8.0 on arch linux, any tips?

**Comment by karpierz** [comment]
Sorry :(
From README:

"Requirements
============

- | It is a fully independent package.
  | All necessary things are installed during the normal installation process.
- ATTENTION: currently works and tested only for Windows.

**Comment by Newbrict** [comment]
ah, I missed that ;(

Do you have any idea how to fix that on linux anyway? I can submit a pr for linux if I figure it out

**Comment by karpierz** [comment]
Hm..
Yes.. I am just during adding of support for Linux, but for now only by the obligatory setting of path to  shared library (libusb.so) in appropriate config file (libusb.cfg).
PS: Bigger problem will be with my 'English'. Sorry ;) I hope you will be forgiving and patient...

**Comment by karpierz** [comment]
@Newbrict 
1.0.22b7 is ready.
It was not tested on Linux.
Can you check if it even starts up?

**Comment by karpierz** [comment]
> 1.0.22b7 is ready.
> It was not tested on Linux.

@Newbrict  @s-light @Heerpa
Internal tests are passed (Debian 10 buster, x64):

(python) root@ks357281:~# git clone https://github.com/karpierz/libusb.git
Cloning into 'libusb'...
[...]
(python) root@ks357281:~# cd libusb/tests
(python) root@ks357281:~/libusb/tests# python stress.py
Starting test run: init_and_exit...
Success (0)
Starting test run: get_device_list...
Success (0)
Starting test run: many_device_lists...
Success (0)
Starting test run: default_context_change...
Success (0)
---
Ran 4 tests
Passed 4 tests
Failed 0 tests
Error in 0 tests
Skipped 0 tests
(python) root@ks357281:~/libusb/tests#

**Comment by karpierz** [comment]
@Newbrict 

Appropriate library (libusb\_platform\_linux\x64\libusb-1.0.so, from Debian 10 buster) has been
included in package.
In addition you can set it manually (e.g. for other platform(s)) by:
LIBUSB = "libusb shared library path" 
i the libusb.libusb.cfg config file.

Thanks,
Adam
