### ISSUE TITLE
Error when trying to run example code hotplugtest.py

### ISSUE THREAD

**Issue by cirossmonteiro** [karpierz/libusb#4]
I created a script named 'usb_test.py' that only contains the code from this file: https://github.com/karpierz/libusb/blob/master/examples/hotplugtest.py

Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Error message:
`Traceback (most recent call last):
  File "/home/*user_name*/random/usb_test.py", line 99, in <module>
    sys.exit(main() or 0)
  File "/home/*user_name*/random/usb_test.py", line 74, in main
    hotplug_callback, None, ct.byref(hp[0]))
TypeError: byref() argument must be a ctypes instance, not 'int'`

**Comment by wingkeet** [comment]
This can be fixed by replacing line 76 with the one below:
**`hp = [usb.hotplug_callback_handle() for i in range(2)]`**

**Comment by karpierz** [comment]
@wingkeet 
Thank you very much.
Issue has been fixed in 1.0.23b7
